#Main Code
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: started
    name: nginx

- name: Downloading Nginx Web Content & Extract it
  ansible.builtin.unarchive:
    url: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp/frontend.zip

- name: Removing Old Web Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: unarchieve a file that needs to be downloaded #hfkhkdc
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes








